strimzi-kafka-operator:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 1000m # Startup boost

  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 20
  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 20

  extraEnvs:
    - name: JAVA_TOOL_OPTIONS
      value: "-Xms256m -Xmx384m -XX:+UseG1GC -Dvertx.blockedThreadCheckInterval=60000"
    - name: STRIMZI_RECONCILIATION_INTERVAL_MS
      value: "120000"

  logLevel: INFO
