apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: nginx
    # Backend (ArgoCD) HTTPS konuşuyor
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

    # ArgoCD'nin kendi sertifikası güvenilir olmadığı için doğrulamayı kapatıyoruz
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"

    # HTTP'den HTTPS'e zorla (Best Practice)
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

    # Upload limiti
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  # Modern K8s standardı: Annotation yerine bu alanı kullanmak daha garantidir
  ingressClassName: nginx
  rules:
    - host: argocd.baranacikgoz.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443 # İsim yerine direkt port numarasını verelim (Daha güvenli)
