apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.10.0
    helm:
      releaseName: ingress-nginx
      parameters:
        - name: controller.service.type
          value: ClusterIP
        - name: controller.ingressClassResource.default
          value: "true"
        - name: controller.watchIngressWithoutClass
          value: "true"

        # 1. Nginx'e "Forwarded" başlıklarını okumasını söyle (Cloudflare HTTPS bilgisini böyle gönderir)
        - name: controller.config.use-forwarded-headers
          value: "true"

        # 2. Proxy IP'lerini hesapla (Güvenlik için)
        - name: controller.config.compute-full-forwarded-for
          value: "true"

        # 3. Global olarak SSL zorlamasını kapat (Ingress kuralları yönetecek)
        - name: controller.config.ssl-redirect
          value: "false"

        - name: controller.resources.requests.cpu
          value: "100m"
        - name: controller.resources.requests.memory
          value: "90Mi"
        - name: controller.resources.limits.memory
          value: "256Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
