data:
  config.yaml: |
    tunnel: k8s-cluster
    ingress:
      # TEK KURAL: Her ÅŸeyi (*.baranacikgoz.com) Nginx'e at
      - hostname: "*.baranacikgoz.com"
        service: http://ingress-nginx-controller.ingress.svc.cluster.local:80
      # Ana domaini de atabilirsin
      - hostname: "baranacikgoz.com"
        service: http://ingress-nginx-controller.ingress.svc.cluster.local:80
      # Kalanlar 404
      - service: http_status:404